version: 2
jobs:
  instruqt-validate:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Validate
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track validate..."
            for dir in $(ls -d /root/project/instruqt-tracks/*); do
              cd $dir && instruqt track validate
            done
  instruqt-test-nomad-basics:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/nomad-basics
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 5
            done
  instruqt-test-nomad-simple-cluster:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/nomad-simple-cluster
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 5
            done
  instruqt-test-nomad-multi-server-cluster:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/nomad-multi-server-cluster
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 5
            done
  instruqt-test-nomad-acls:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/nomad-acls
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 5
            done
  instruqt-test-nomad-monitoring:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/nomad-monitoring
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 5
            done
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - instruqt-validate:
          filters:
            branches:
              only: master
      - instruqt-test-nomad-basics:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: master
      - instruqt-test-nomad-simple-cluster:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: master
      - instruqt-test-nomad-multi-server-cluster:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: master
      - instruqt-test-nomad-acls:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: master
      - instruqt-test-nomad-monitoring:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: master
  nightly-build:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - instruqt-validate
      - instruqt-test-nomad-basics:
          requires:
            - instruqt-validate
      - instruqt-test-nomad-simple-cluster:
          requires:
            - instruqt-validate
      - instruqt-test-nomad-multi-server-cluster:
          requires:
            - instruqt-validate
      - instruqt-test-nomad-acls:
          requires:
            - instruqt-validate
      - instruqt-test-nomad-monitoring:
          requires:
            - instruqt-validate
